#!/bin/bash

HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="Skripta za provođenje CRUD operacija nad jednim ili više korisničkih računa"
TITLE="Title here"
MENU="Choose one of the following options:"

OPTIONS=(1 "Option 1" 2 "Option 2"
    3 "Option 3")
OPTIONS2=(4 "Option 4")

CHOICE=$(dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "$TITLE" \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

CHOICE2=$(dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "$TITLE" \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS2[@]}" \
    2>&1 >/dev/tty)

clear
case $CHOICE in
1)
    case $CHOICE2 in
    4)
        echo "You chose Option 4"
        ;;
    esac
    ;;
2)
    echo "You chose Option 2"
    ;;
3)
    echo "You chose Option 3"
    ;;
esac
