#!/bin/bash

# provjeriti je li korisnik admin
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Skriptu morate pokrenuti kao admin!"
    exit
fi

kreiranjeKorisnika() {
    #TODO provjeriti je li ime vec postoji
    echo "Upišite novo korisničko ime: "
    read newUsername
    useradd -m "$newUsername"
    if [ $? -eq 0 ]; then
        echo "Uspješno kreirano ime!"
    else
        echo "Greška. Pokušajte ponovno."
        exit
    fi
    passwd "$newUsername"
    if [ $? -eq 0 ]; then
        echo "Uspješno kreirano!"
    else
        echo "Greška. Pokušajte ponovno."
        exit
    fi
}

brisanjeKorisnika() {
    #TODO provjeriti je li ime postoji
    echo "Upišite račun koji želite obrisati: "
    read oldUsername
    userdel -r "$oldUsername"
    if [ $? -eq 0 ]; then
        echo "Uspješno izbrisano!"
    else
        echo "Greška. Ako dobijete error: 'user <oldname> is currently used by process <processno>' morate zaustaviti taj proces sa naredbom: kill <processno>."
        echo "Ako želite izbrisati trenutno korištenog korisnika, morate se prijaviti na drugi račun te sa njega obrisati željeni račun."
        exit
    fi
}

sviRacuni() {
    # less /etc/passwd | cut -d: -f1
    echo "----------------"
    cut -d: -f1,3 /etc/passwd | egrep ':[0-9]{4}$' | cut -d: -f1
}

azuriranjeImena() {
    #TODO provjeriti je li takvo ime postoji, ako da dobro, ako ne, greska
    echo "Upiši staro korisničko ime"
    read name
    echo "Upiši novo korisničko ime"
    read new
    usermod -l "$new" "$name"
    usermod -d /home/"$new" -m "$new"
    if [ $? -eq 0 ]; then
        echo "Uspješno ažurirano!"
    else
        echo "Greška. Ako dobijete error: 'user <oldname> is currently used by process <processno>' morate zaustaviti taj proces sa naredbom: kill <processno>."
        echo "Ako želite promijeniti ime ili lozinku trenutno korištenog korisnika, morate se prijaviti na drugi račun te sa njega ažurirati željeni račun."
        exit
    fi
}

azuriranjeLozinke() {
    echo "Upišite korisničko ime:"
    read korisnickoIme
    passwd "$korisnickoIme"
    if [ $? -eq 0 ]; then
        echo "Uspješno ažurirano!"
    else
        echo "Greška. Ako dobijete error: 'user <oldname> is currently used by process <processno>' morate zaustaviti taj proces sa naredbom: kill <processno>."
        echo "Ako želite promijeniti ime ili lozinku trenutno korištenog korisnika, morate se prijaviti na drugi račun te sa njega ažurirati željeni račun."
        exit
    fi
}

opcijeJedan=("Pregled svih računa na računalu" "Kreiranje računa" "Ažuriranje računa" "Brisanje računa" "Kraj")
opcijeVise=("Ispis računa" "Odabir JSON-a" "Ispis sadržaja JSON-a" "Kraj")
#TODO napisati opcije za vise opcijeViše

izborAzuriranja() {
    select izbor in Ime Lozinka; do
        case $izbor in
        Ime)
            azuriranjeImena
            break
            ;;
        Lozinka)
            azuriranjeLozinke
            break
            ;;

        *)
            echo "Kriva naredba! Ponovite"
            break
            ;;
        esac
    done
}

# Select Menu
echo "Skripta za provođenje CRUD operacija nad jednim ili više korisničkih računa"
echo ""
PS3="Odaberite opciju:"

while true; do
    echo "----------------"
    select opcija in Jedan Višestruko Kraj; do
        case $opcija in
        Jedan)
            while true; do
                echo "----------------"
                select podopcija in "${opcijeJedan[@]}"; do
                    case $podopcija in
                    "Pregled svih računa na računalu")
                        sviRacuni
                        break 3
                        ;;
                    "Kreiranje računa")
                        kreiranjeKorisnika
                        break
                        ;;
                    "Ažuriranje računa")
                        izborAzuriranja
                        break
                        ;;
                    "Brisanje računa")
                        brisanjeKorisnika
                        break
                        ;;
                    "Kraj")
                        exit
                        ;;
                    *)
                        echo "Kriva naredba! Ponovite"
                        break
                        ;;
                    esac
                done
            done
            ;;
        Višestruko)
            while true; do
                echo "----------------"
                select podopcija in "${opcijeVise[@]}"; do
                    case $podopcija in
                    "Ispis računa")
                        json="$1"
                        cat $json | jq '.users[0]'
                        break 3
                        ;;
                    "Odabir JSON-a")
                        datoteka=$(zenity --file-selection --title="Odaberite .json datoteku" --file-filter="*.json" 2>/dev/null)
                        if [ $? -eq 0 ]; then
                            echo "JSON uspješno učitan!"
                        else
                            echo "Greška. Ponovite"
                            exit
                        fi
                        sadrzaj=$(cat $datoteka | jq '.users')
                        if [ "$sadrzaj" = null ]; then
                            echo "Neispravni JSON! Pokušajte ponovno."
                            echo "Primjer ispravnog formata:"
                            echo "{"
                            echo "  "users": ["
                            echo "      {"
                            echo "         "username": "...","
                            echo "         "password": "...""
                            echo "      },"
                            echo "        ..."
                            echo "   ]"
                            echo "}"

                        else
                            echo "$sadrzaj"
                        fi
                        break
                        ;;
                    "Ispis sadržaja JSON-a")
                        echo "$sadrzaj"
                        break
                        ;;
                    "Kraj")
                        exit
                        ;;
                    *)
                        echo "Kriva naredba! Ponovite"
                        break
                        ;;
                    esac
                done
            done
            ;;
        Kraj)
            break 2
            ;;
        *)
            echo "Kriva naredba! Ponovite"
            break
            ;;
        esac
    done
done

# Giving a JSON file to the script and displaying the first object
#json="$1"
#cat $json | jq '.users[0]'

#using zenity for file selection
