#!/bin/bash

options=("Pregled svih računa na računalu" "Kreiranje računa" "Ažuriranje računa" "Brisanje računa")

# Select Menu
echo "Skripta za provođenje CRUD operacija nad jednim ili više korisničkih računa"
echo ""
PS3="Odaberite opciju:"

while true; do
    select opcija in Jedan Višestruko Kraj
    do
        case $opcija in
            Jedan)
                select podopcija in "${options[@]}"
                do
                    case $podopcija in
                        "Pregled svih računa na računalu")
                            echo "uspjeh"
                            break 2
                            ;;
                    esac
                done
            ;;
            *)
                echo "kraj"
                break 2
        esac
    done
done



# Giving a JSON file to the script and displaying the first object
#json="$1"
#cat $json | jq '.users[0]'