#!/bin/bash

# provjeriti je li korisnik admin
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Skriptu morate pokrenuti kao admin!"
    exit
fi

sviRacuni() {
    # less /etc/passwd | cut -d: -f1
    cut -d: -f1,3 /etc/passwd | egrep ':[0-9]{4}$' | cut -d: -f1
}

azuriranjeImena() {
    #TODO provjeriti je li takvo ime postoji, ako da dobro, ako ne, greska
    echo "Give me the old username"
    read name
    echo "Give me the new username"
    read new
    usermod -l "$new" "$name"
    usermod -d /home/"$new" -m "$new"
    #TODO s obzirom je li prosla naredba ispisi poruku
}

options=("Pregled svih računa na računalu" "Kreiranje računa" "Ažuriranje računa" "Brisanje računa")

# Select Menu
echo "Skripta za provođenje CRUD operacija nad jednim ili više korisničkih računa"
echo ""
PS3="Odaberite opciju:"

while true; do
    echo "----------------"
    select opcija in Jedan Višestruko Kraj; do
        case $opcija in
        Jedan)
            while true; do
                select podopcija in "${options[@]}"; do
                    case $podopcija in
                    "Pregled svih računa na računalu")
                        sviRacuni
                        break 3
                        ;;
                    "Kreiranje računa")
                        echo "uspjeh"
                        break
                        ;;
                    "Ažuriranje računa")
                        azuriranjeImena
                        echo "uspjeh"
                        break
                        ;;
                    *)
                        echo "Kriva naredba! Ponovite"
                        break
                        ;;
                    esac
                done
            done
            ;;
        Kraj)
            echo "kraj"
            break 2
            ;;
        *)
            echo "Kriva naredba! Ponovite"
            break
            ;;
        esac
    done
done

# Giving a JSON file to the script and displaying the first object
#json="$1"
#cat $json | jq '.users[0]'
